locales = {
'Русский': {
                'main_menu': 'Главное меню',
                'play': 'Играть',
                'completed_levels': 'Пройденные уровни',
                'achievements': 'Достижения',
                'settings': 'Настройки',
                'reset': 'Сбросить прогресс',
                'exit': 'Выйти',
                'score': 'Очки',
                'select_root': 'Выберите корень',
                'guessed': 'Угадано',
                'hint': 'Подсказка',
                'check': 'Проверить',
                'clear': 'Очистить поле',
                'remove': 'Удалить последнюю',
                'back': 'Назад',
                'correct': 'Правильно!',
                'error': 'Ошибка',
                'word_exists': 'Слово существует, но образуется по-другому!',
                'word_not_exists': 'Такого слова не существует!',
                'level_completed': 'Уровень пройден!',
                'all_words_guessed': 'Все слова отгаданы! +50 бонусных очков',
                'word_already_guessed': 'Это слово уже отгадано!',
                'hint_cost': 'Подсказка (30)',
                'not_enough_points': 'Недостаточно очков для подсказки!',
                'no_hints_available': 'Нет доступных слов для подсказки!',
                'settings_applied': 'Изменения применены!',
                'interface_lang': 'Язык интерфейса',
                'translation_lang': 'Язык перевода',
                'window_size': 'Размер окна',
                'fullscreen': 'Полноэкранный режим',
                'apply': 'Применить',
                'cancel': 'Отмена',
                'translation_error': 'Ошибка перевода',
                'root_explanation': 'Пояснение корня',
                'no_explanation': 'Пояснение отсутствует',
                'guessed_words': 'Отгаданные слова',
                'nouns': 'Существительные',
                'adjectives': 'Прилагательные',
                'verbs': 'Глаголы',
                'adverbs': 'Наречия',
                'prefix_formation': 'Приставочное образование',
                'suffix_formation': 'Суффиксальное образование',
                'reset_confirm': 'Прогресс и очки сброшены!',
                'no_completed_levels': 'Пока нет пройденных уровней',
                'achievement_unlocked': 'Достижение!',
                'current_score': 'Текущий счёт',
                'words_guessed': 'Угадано слов',
                'prefix': 'Приставка',
                'suffix': 'Суффикс',
                'no_hints_achievement': 'Отгадано 10 слов без подсказок',
                'word_master_achievement': 'Отгадано 50 слов',
                'economist_achievement': 'Накоплено 500 очков',
                'no_hints_title': 'Чистая победа',
                'no_hints_desc': 'Отгадать 10 слов без использования подсказок',
                'word_master_title': 'Мастер словообразования',
                'word_master_desc': 'Отгадать 50 слов',
                'economist_title': 'Экономист',
                'economist_desc': 'Накопить 500 очков',
                'confirm_reset': 'Вы уверены, что хотите сбросить прогресс?',
                'explanation': 'Пояснение',
                'translation': 'Перевод'
            },
            'English': {
                'main_menu': 'Main Menu',
                'play': 'Play',
                'completed_levels': 'Completed Levels',
                'achievements': 'Achievements',
                'settings': 'Settings',
                'reset': 'Reset Progress',
                'exit': 'Exit',
                'score': 'Score',
                'select_root': 'Select Root',
                'guessed': 'Guessed',
                'hint': 'Hint',
                'check': 'Check',
                'clear': 'Clear Field',
                'remove': 'Remove Last',
                'back': 'Back',
                'correct': 'Correct!',
                'error': 'Error',
                'word_exists': 'Word exists but formed differently!',
                'word_not_exists': 'Word does not exist!',
                'level_completed': 'Level completed!',
                'all_words_guessed': 'All words guessed! +50 bonus points',
                'word_already_guessed': 'This word is already guessed!',
                'hint_cost': 'Hint (30)',
                'not_enough_points': 'Not enough points for a hint!',
                'no_hints_available': 'No words available for hints!',
                'settings_applied': 'Changes applied!',
                'interface_lang': 'Interface Language',
                'translation_lang': 'Translation Language',
                'window_size': 'Window Size',
                'fullscreen': 'Fullscreen Mode',
                'apply': 'Apply',
                'cancel': 'Cancel',
                'translation_error': 'Translation Error',
                'root_explanation': 'Root Explanation',
                'no_explanation': 'No explanation available',
                'guessed_words': 'Guessed Words',
                'nouns': 'Nouns',
                'adjectives': 'Adjectives',
                'verbs': 'Verbs',
                'adverbs': 'Adverbs',
                'prefix_formation': 'Prefix Formation',
                'suffix_formation': 'Suffix Formation',
                'reset_confirm': 'Progress and scores reset!',
                'no_completed_levels': 'No completed levels yet',
                'achievement_unlocked': 'Achievement Unlocked!',
                'current_score': 'Current score',
                'words_guessed': 'Words guessed',
                'prefix': 'Prefix',
                'suffix': 'Suffix',
                'no_hints_achievement': 'Guessed 10 words without hints',
                'word_master_achievement': 'Guessed 50 words',
                'economist_achievement': 'Earned 500 points',
                'no_hints_title': 'Clean Victory',
                'no_hints_desc': 'Guess 10 words without using hints',
                'word_master_title': 'Word Formation Master',
                'word_master_desc': 'Guess 50 words',
                'economist_title': 'Economist',
                'economist_desc': 'Earn 500 points',
                'confirm_reset': 'Are you sure you want to reset progress?',
                'explanation': 'Explanation',
                'translation': 'Translation'
            },
            '中文': {
                'main_menu': '主菜单',
                'play': '玩',
                'completed_levels': '完成的关卡',
                'achievements': '成就',
                'settings': '设置',
                'reset': '重置进度',
                'exit': '退出',
                'score': '分数',
                'select_root': '选择词根',
                'guessed': '已猜',
                'hint': '提示',
                'check': '检查',
                'clear': '清空',
                'remove': '删除最后',
                'back': '返回',
                'correct': '正确!',
                'error': '错误',
                'word_exists': '单词存在但形式不同!',
                'word_not_exists': '单词不存在!',
                'level_completed': '关卡完成!',
                'all_words_guessed': '所有单词已猜出! +50 奖励分',
                'word_already_guessed': '这个单词已经猜过了!',
                'hint_cost': '提示 (30)',
                'not_enough_points': '点数不足无法获取提示!',
                'no_hints_available': '没有可用的提示单词!',
                'settings_applied': '设置已应用!',
                'interface_lang': '界面语言',
                'translation_lang': '翻译语言',
                'window_size': '窗口大小',
                'fullscreen': '全屏模式',
                'apply': '应用',
                'cancel': '取消',
                'translation_error': '翻译错误',
                'root_explanation': '词根解释',
                'no_explanation': '无解释',
                'guessed_words': '已猜单词',
                'nouns': '名词',
                'adjectives': '形容词',
                'verbs': '动词',
                'adverbs': '副词',
                'prefix_formation': '前缀构词',
                'suffix_formation': '后缀构词',
                'reset_confirm': '进度和分数已重置!',
                'no_completed_levels': '暂无完成的关卡',
                'achievement_unlocked': '成就达成!',
                'current_score': '当前分数',
                'words_guessed': '已猜单词',
                'prefix': '前缀',
                'suffix': '后缀',
                'no_hints_achievement': '不提示猜出10个单词',
                'word_master_achievement': '猜出50个单词',
                'economist_achievement': '累积500分',
                'no_hints_title': '纯净胜利',
                'no_hints_desc': '不使用提示猜出10个单词',
                'word_master_title': '构词大师',
                'word_master_desc': '猜出50个单词',
                'economist_title': '经济学家',
                'economist_desc': '累积500分',
                'confirm_reset': '确定要重置进度吗?',
                'explanation': '解释说明',
                'translation': '翻译'
            }
        }